### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by airyland** [airyland/vue-tracker#1]
+ [ ] click event track
+ [ ] pageview track, including duration
+ [ ] save locally and send when entering again
